language: node_js
node_js:
- 4.2.2
before_install:
- npm i -g npm@^3.0.0
before_script:
  - npm install
script: gulp prod
deploy:
  provider: heroku
  api_key:
    secure: SdHQg3RTK5K/HTnI+gKssJtqfV+8D55vFEnqUXBDxvY2Av2AA3iOuAxqLLHO/g2hPR+tbcbCzwC4zQxxBSD0QKyIFIqaHL7rO7FKb2/h/MWkut1UFM8KF998Mq3cZ58TUn8xsjquYfdhz7QU4FWuileMHDMf8JFcYG2b7V/hH6UoEubo2/GWNhtoi9sdSphNqSpIV4gR41tEDdo39gO7i38ZPBF66ZUG++N5piIKkjJBaMAHA2alWG/jyIy18tsD0P4E0yrnGB+0v8fgyw0SjgN7shRHmbA/tEvxbHJw68GXizGlzp50VhnU8C+Z2NeRvgtH2Xq+6hr66AaDWSwPf6kJlwBm8Bz6cgHS2jY29EFMglGUL96NKLaKMpEBZOP04fZXUnZbk2k2r0w6yIQSVg20rMTeJfgFzrJJgPNIir3pBA0V6flOSydBBsXY8cc4LZJ+c4q+uPkqsecoNmaaLK0841UXMKJZqGfSLhT+Hi3KXAejz5yVQdfnjvnDZA211slSB1jN6DlPPaZYuq6sfs74G41DdbBjrVwFMqgwnmHShzhNEviS8UWYXlVDO1ZmJfO0DGo7gdQ3aNr7AfJpNxAxQDKHiDbsUvNb4kpxnUEuMmFnLClDvHrtGHe9gIP1cb5gdDucKTULovRj52PBsMXerJIKhIgvdYMy/13XrZA=
